import type { AuthSlide } from './components/AuthSplitShell'

// 后续替换图片/视频时，在对应 point 上添加 imageSrc 或 videoSrc。
// 每个 point 就是图片区轮播的一帧，也对应左侧一个可点击要点。
// 示例：videoSrc: agentNativeVideo, videoType: 'video/mp4', imageAlt: '原生 Agent 演示视频'
export const AUTH_SLIDES: AuthSlide[] = [
  {
    id: 'slide-01',
    eyebrow: 'Agent',
    title: '广泛的智能体选择',
    description: '从本地原生 Agent 到 Dify 工作流，再到你的小龙虾助手，把不同任务交给最合适的智能体。',
    accent: 'pink',
    points: [
      {
        id: 'agent-native',
        title: '原生 Agent',
        description: '在 SuperLeaf 内创建、配置并运行原生 Agent，绑定模型、技能与项目上下文。',
        visualLabel: '预留图 A',
        visualTitle: '原生 Agent 管理界面',
        visualHint: '建议放 Team / Agent 配置面板截图',
      },
      {
        id: 'agent-lobster',
        title: '你的小龙虾',
        description: '保留个性化助手入口，用熟悉的角色承接开放任务、润色、复核和灵感生成。',
        visualLabel: '预留图 B',
        visualTitle: '个性化助手对话',
        visualHint: '建议放对话或助手详情截图',
      },
      {
        id: 'agent-dify',
        title: 'Dify',
        description: '接入 Dify ，把已有外部工作流纳入写作流程。',
        visualLabel: '预留图 C',
        visualTitle: 'Dify 提供商与运行结果',
        visualHint: '建议放 Dify provider 或运行轨迹截图',
      },
    ],
  },
  {
    id: 'slide-02',
    eyebrow: 'Skill',
    title: '灵活的 Skill 配置',
    description: '技能可以来自市场、私有上传或项目自定义，让每个 Agent 只携带当前任务需要的能力。',
    accent: 'blue',
    points: [
      {
        id: 'skill-market',
        title: 'Skill 市场',
        description: '从官方或团队市场安装技能，快速补齐审稿、格式检查、资料处理等能力。',
        visualLabel: '预留图 A',
        visualTitle: 'Skill Marketplace',
        visualHint: '建议放技能市场列表或安装弹窗截图',
      },
      {
        id: 'skill-upload',
        title: '私有上传',
        description: '上传只属于当前团队或项目的 Skill，保护内部流程和提示资产。',
        visualLabel: '预留图 B',
        visualTitle: '上传私有 Skill',
        visualHint: '建议放上传表单或私有 Skill 详情截图',
      },
      {
        id: 'skill-custom',
        title: '自定义绑定',
        description: '按 Agent 分配技能，避免能力过载，也方便复现同一套写作流水线。',
        visualLabel: '预留图 C',
        visualTitle: 'Agent Skill 分配',
        visualHint: '建议放 Agent 绑定 Skill 的配置截图',
      },
    ],
  },
  {
    id: 'slide-03',
    eyebrow: 'MCP',
    title: 'MCP 工具接入',
    description: '把外部工具作为可审计、可配置的能力接入 Agent，让写作任务能触达文件、数据和服务。',
    accent: 'peach',
    points: [
      {
        id: 'mcp-catalog',
        title: '工具目录',
        description: '通过 MCP catalog 管理可用工具，区分官方预设、团队预设和自定义服务。',
        visualLabel: '预留图 A',
        visualTitle: 'MCP 工具目录',
        visualHint: '建议放 MCP catalog 或工具列表截图',
      },
      {
        id: 'mcp-probe',
        title: '连通性检查',
        description: '在交给 Agent 使用前先探测服务状态，减少运行时失败。',
        visualLabel: '预留图 B',
        visualTitle: 'MCP Probe 结果',
        visualHint: '建议放连接测试或 golden test 截图',
      },
      {
        id: 'mcp-runtime',
        title: '按需调用',
        description: 'Agent 执行时再拉起工具，降低常驻进程和权限暴露。',
        visualLabel: '预留图 C',
        visualTitle: 'Agent 调用 MCP 工具',
        visualHint: '建议放运行日志或工具调用结果截图',
      },
    ],
  },
  {
    id: 'slide-04',
    eyebrow: 'Workflow',
    title: '可编排的工作流',
    description: '把多个 Agent、循环节点和测试运行组合起来，形成可保存、可复用、可观察的研究写作流程。',
    accent: 'mint',
    points: [
      {
        id: 'workflow-canvas',
        title: '可视化编排',
        description: '在画布上组织 Agent 与循环节点，直观看到输入、输出和执行路径。',
        visualLabel: '预留图 A',
        visualTitle: 'Workflow Canvas',
        visualHint: '建议放工作流画布截图',
      },
      {
        id: 'workflow-test',
        title: '测试运行',
        description: '正式应用前先用样例输入跑一遍，检查节点输出和失败位置。',
        visualLabel: '预留图 B',
        visualTitle: 'Workflow Test Run',
        visualHint: '建议放测试运行面板截图',
      },
      {
        id: 'workflow-history',
        title: '运行追踪',
        description: '每次执行留下可回看轨迹，方便复盘 Agent 决策和中间结果。',
        visualLabel: '预留图 C',
        visualTitle: 'Run History',
        visualHint: '建议放运行历史或 trace 截图',
      },
    ],
  },
  {
    id: 'slide-05',
    eyebrow: 'Collaboration',
    title: '实时协同写作',
    description: '编辑器、项目文件和讨论上下文一起协作，团队成员与 Agent 都围绕同一份稿件工作。',
    accent: 'pink',
    points: [
      {
        id: 'collab-editing',
        title: '多人实时编辑',
        description: '基于 Yjs 的协同编辑，让多人同时处理 LaTeX 文稿和项目内容。',
        visualLabel: '预留图 A',
        visualTitle: '实时编辑状态',
        visualHint: '建议放编辑器多人 presence 截图',
      },
      {
        id: 'collab-discussion',
        title: '讨论数据',
        description: '讨论与当前文档绑定，Agent 回复、人工意见和附件都能留在上下文中。',
        visualLabel: '预留图 B',
        visualTitle: 'Discussion 面板',
        visualHint: '建议放右侧讨论面板截图',
      },
      {
        id: 'collab-mentions',
        title: '@ 你的 Agent 助手',
        description: '通过 @ 提醒 Agent 来干活啦。',
        visualLabel: '预留图 C',
        visualTitle: '@ Mention 输入',
        visualHint: '建议放 @ 候选或附件 chips 截图',
      },
    ],
  },
  {
    id: 'slide-06',
    eyebrow: 'Versioning',
    title: '版本管理与归档',
    description: '从文档历史到项目归档，把重要修改、里程碑和可交付版本稳定保留下来。',
    accent: 'blue',
    points: [
      {
        id: 'version-history',
        title: '文档历史',
        description: '查看文档变更记录，对比重要差异，回到清晰的修改节点。',
        visualLabel: '预留图 A',
        visualTitle: 'History / Diff',
        visualHint: '建议放版本差异或历史列表截图',
      },
      {
        id: 'version-major',
        title: 'Major Version',
        description: '为关键阶段创建里程碑版本，便于团队审阅和阶段交付。',
        visualLabel: '预留图 B',
        visualTitle: 'Major Version 列表',
        visualHint: '建议放 Major Version 面板截图',
      },
      {
        id: 'version-archive',
        title: '项目归档',
        description: '将项目打包归档，保留源文件、结构和后续恢复入口。',
        visualLabel: '预留图 C',
        visualTitle: 'Project Archive',
        visualHint: '建议放项目归档或下载面板截图',
      },
    ],
  },
]
