import type { AuthSlide } from './components/AuthSplitShell'

// 后续替换图片/视频时，在对应 point 上添加 imageSrc 或 videoSrc。
// 每个 point 就是图片区轮播的一帧，也对应左侧一个可点击要点。
// 示例：videoSrc: agentNativeVideo, videoType: 'video/mp4', imageAlt: '原生 Agent 演示视频'
export const AUTH_SLIDES: AuthSlide[] = [
  {
    id: 'slide-01',
    eyebrow: 'Agent',
    title: '多种 Agent，各司其职',
    description: '从原生 Agent 到 Dify 工作流，再到你的专属小龙虾助手——把每项任务交给最擅长它的智能体。',
    accent: 'pink',
    points: [
      {
        id: 'agent-native',
        title: '🤖 原生 Agent',
        description: '在 SuperLeaf 内创建专属 Agent，绑定模型、技能与项目上下文，一站式运行。',
        visualLabel: '预留图 A',
        visualTitle: '原生 Agent 管理界面',
        visualHint: '建议放 Team / Agent 配置面板截图',
      },
      {
        id: 'agent-lobster',
        title: '🦞 你的小龙虾',
        description: '你的个性化写作伙伴，承接润色、复核、灵感激发等开放任务。',
        visualLabel: '预留图 B',
        visualTitle: '个性化助手对话',
        visualHint: '建议放对话或助手详情截图',
      },
      {
        id: 'agent-dify',
        title: '⚡ Dify 工作流',
        description: '无缝接入 Dify，将已有的外部工作流融入你的写作流程。',
        visualLabel: '预留图 C',
        visualTitle: 'Dify 提供商与运行结果',
        visualHint: '建议放 Dify provider 或运行轨迹截图',
      },
    ],
  },
  {
    id: 'slide-02',
    eyebrow: 'Skill',
    title: '按需装配，精准赋能',
    description: '技能来自市场、私有上传或项目自定义——每个 Agent 只携带当前任务需要的能力，不多不少。',
    accent: 'blue',
    points: [
      {
        id: 'skill-market',
        title: '开放市场',
        description: '从公开市场一键安装，快速获得审稿、格式检查、文献处理等专业技能。',
        visualLabel: '预留图 A',
        visualTitle: 'Skill Marketplace',
        visualHint: '建议放技能市场列表或安装弹窗截图',
      },
      {
        id: 'skill-upload',
        title: '私有上传',
        description: '上传团队专属 Skill，保护内部流程与提示资产不外泄。',
        visualLabel: '预留图 B',
        visualTitle: '上传私有 Skill',
        visualHint: '建议放上传表单或私有 Skill 详情截图',
      },
      {
        id: 'skill-custom',
        title: '协同共创',
        description: 'Skill 项目与写作项目相互打通，在使用中持续迭代优化技能。',
        visualLabel: '预留图 C',
        visualTitle: 'Agent Skill 分配',
        visualHint: '建议放 Agent 绑定 Skill 的配置截图',
      },
    ],
  },
  {
    id: 'slide-03',
    eyebrow: 'MCP',
    title: '工具触手可及，用时再启动',
    description: '把外部工具接入 Agent，写作任务即可触达文件、数据和外部服务——按需调用，不常驻。',
    accent: 'peach',
    points: [
      {
        id: 'mcp-catalog',
        title: '工具目录',
        description: '通过 MCP Catalog 管理可用工具，区分官方预设、团队预设与自定义服务。',
        visualLabel: '预留图 A',
        visualTitle: 'MCP 工具目录',
        visualHint: '建议放 MCP catalog 或工具列表截图',
      },
      {
        id: 'mcp-probe',
        title: '先探测，再使用',
        description: '调用前自动检测服务连通性，把运行时错误扼杀在配置阶段。',
        visualLabel: '预留图 B',
        visualTitle: 'MCP Probe 结果',
        visualHint: '建议放连接测试或 golden test 截图',
      },
      {
        id: 'mcp-runtime',
        title: '按需拉起',
        description: 'Agent 执行时才启动工具进程，降低资源占用与权限暴露风险。',
        visualLabel: '预留图 C',
        visualTitle: 'Agent 调用 MCP 工具',
        visualHint: '建议放运行日志或工具调用结果截图',
      },
    ],
  },
  {
    id: 'slide-04',
    eyebrow: 'Workflow',
    title: '设计流程，验证想法，追踪每一步',
    description: '用可视化画布编排多 Agent 协作，测试运行验证节点输出，运行历史记录每一次决策。',
    accent: 'mint',
    points: [
      {
        id: 'workflow-canvas',
        title: '可视化画布',
        description: '在画布上拖拽编排 Agent 与循环节点，输入输出一目了然。',
        visualLabel: '预留图 A',
        visualTitle: 'Workflow Canvas',
        visualHint: '建议放工作流画布截图',
      },
      {
        id: 'workflow-test',
        title: '测试运行',
        description: '正式跑之前先用样例数据验证，提前发现节点输出问题。',
        visualLabel: '预留图 B',
        visualTitle: 'Workflow Test Run',
        visualHint: '建议放测试运行面板截图',
      },
      {
        id: 'workflow-history',
        title: '运行追踪',
        description: '每次执行留下完整轨迹，方便复盘 Agent 决策与中间结果。',
        visualLabel: '预留图 C',
        visualTitle: 'Run History',
        visualHint: '建议放运行历史或 trace 截图',
      },
    ],
  },
  {
    id: 'slide-05',
    eyebrow: 'Collaboration',
    title: '人与 Agent，并肩写作',
    description: '多人实时编辑同一份文稿，Agent 通过 @ 即刻参与——讨论、编辑、审稿都在同一个上下文里完成。',
    accent: 'pink',
    points: [
      {
        id: 'collab-editing',
        title: '多人实时编辑',
        description: '基于 Yjs CRDT 的协同编辑，多人同时处理 LaTeX 文稿，冲突自动合并。',
        visualLabel: '预留图 A',
        visualTitle: '实时编辑状态',
        visualHint: '建议放编辑器多人 presence 截图',
      },
      {
        id: 'collab-discussion',
        title: '讨论即上下文',
        description: '讨论与文档绑定，Agent 回复、人工意见、附件都留在写作上下文中。',
        visualLabel: '预留图 B',
        visualTitle: 'Discussion 面板',
        visualHint: '建议放右侧讨论面板截图',
      },
      {
        id: 'collab-mentions',
        title: '@ 唤起 Agent',
        description: '在编辑器中 @ 你的 Agent，它会带着当前文档上下文立即响应。',
        visualLabel: '预留图 C',
        visualTitle: '@ Mention 输入',
        visualHint: '建议放 @ 候选或附件 chips 截图',
      },
    ],
  },
  {
    id: 'slide-06',
    eyebrow: 'Versioning',
    title: '双层版本，放心回溯',
    description: '文档级历史追踪每一处改动，项目级里程碑锁定关键节点——任何时候都能安心回退。',
    accent: 'blue',
    points: [
      {
        id: 'version-history',
        title: '文档历史',
        description: '逐条查看变更记录，对比差异，一键回到任意历史版本。',
        visualLabel: '预留图 A',
        visualTitle: 'History / Diff',
        visualHint: '建议放版本差异或历史列表截图',
      },
      {
        id: 'version-major',
        title: '里程碑版本',
        description: '为关键阶段创建 Major Version，便于团队审阅与阶段交付。',
        visualLabel: '预留图 B',
        visualTitle: 'Major Version 列表',
        visualHint: '建议放 Major Version 面板截图',
      },
      {
        id: 'version-archive',
        title: '项目归档',
        description: '打包归档整个项目，保留源文件与结构，随时可恢复。',
        visualLabel: '预留图 C',
        visualTitle: 'Project Archive',
        visualHint: '建议放项目归档或下载面板截图',
      },
    ],
  },
]
