import type { AuthSlide } from './components/AuthSplitShell'

export const AUTH_SLIDES: AuthSlide[] = [
  {
    id: 'slide-01',
    eyebrow: 'Slide 01',
    title: '安装',
    description: '这里先预留第一页的简介说明，后续你只需要替换文案，不用改组件结构。',
    bullets: ['第一页要点 1', '第一页要点 2', '第一页要点 3'],
    accent: 'pink',
    imageSrc: undefined,
    imageAlt: '第一页配图',
  },
  {
    id: 'slide-02',
    eyebrow: 'Slide 02',
    title: '首次启动',
    description: '这里先预留第二页的简介说明，方便后续直接替换成你的正式内容。',
    bullets: ['第二页要点 1', '第二页要点 2', '第二页要点 3'],
    accent: 'blue',
    imageSrc: undefined,
    imageAlt: '第二页配图',
  },
  {
    id: 'slide-03',
    eyebrow: 'Slide 03',
    title: '原生Agent',
    description: '保持统一结构后，七页内容都可以独立替换，同时保留一致的视觉效果。',
    bullets: ['第三页要点 1', '第三页要点 2', '第三页要点 3'],
    accent: 'peach',
    imageSrc: undefined,
    imageAlt: '第三页配图',
  },
  {
    id: 'slide-04',
    eyebrow: 'Slide 04',
    title: 'MCP工具',
    description: '这一页可用于放功能亮点、协作能力或产品流程中的关键一环。',
    bullets: ['第四页要点 1', '第四页要点 2', '第四页要点 3'],
    accent: 'mint',
    imageSrc: undefined,
    imageAlt: '第四页配图',
  },
  {
    id: 'slide-05',
    eyebrow: 'Slide 05',
    title: '工作流',
    description: '这一页适合强调体验收益、使用场景，或者与团队协作相关的价值。',
    bullets: ['第五页要点 1', '第五页要点 2', '第五页要点 3'],
    accent: 'pink',
    imageSrc: undefined,
    imageAlt: '第五页配图',
  },
  {
    id: 'slide-06',
    eyebrow: 'Slide 06',
    title: '编辑器',
    description: '这里可以放流程、自动化、版本管理、运行记录等偏系统能力的信息。',
    bullets: ['第六页要点 1', '第六页要点 2', '第六页要点 3'],
    accent: 'blue',
    imageSrc: undefined,
    imageAlt: '第六页配图',
  },
  {
    id: 'slide-07',
    eyebrow: 'Slide 07',
    title: '版本归档',
    description: '最后一页通常适合收束价值表达，作为整个左侧 PPT 的总结与落点。',
    bullets: ['第七页要点 1', '第七页要点 2', '第七页要点 3'],
    accent: 'peach',
    imageSrc: undefined,
    imageAlt: '第七页配图',
  },
]
